"""Page Studio and global structure"""
from alembic import op
import sqlalchemy as sa
revision="0002_page_studio"; down_revision="0001_foundation"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("cms_pages",sa.Column("id",sa.String(36),primary_key=True),sa.Column("route",sa.String(240),nullable=False),sa.Column("slug",sa.String(180),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("template",sa.String(80),nullable=False,server_default="standard"),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("show_in_navigation",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("is_indexable",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("seo_title",sa.String(180),nullable=False,server_default=""),sa.Column("meta_description",sa.String(320),nullable=False,server_default=""),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("route")); op.create_index("ix_cms_pages_route","cms_pages",["route"],unique=True); op.create_index("ix_cms_pages_status","cms_pages",["status"]); op.create_index("ix_cms_pages_slug","cms_pages",["slug"])
    op.create_table("cms_page_sections",sa.Column("id",sa.String(36),primary_key=True),sa.Column("page_id",sa.String(36),sa.ForeignKey("cms_pages.id",ondelete="CASCADE"),nullable=False),sa.Column("section_key",sa.String(120),nullable=False),sa.Column("section_type",sa.String(80),nullable=False),sa.Column("position",sa.Integer(),nullable=False),sa.Column("is_enabled",sa.Boolean(),nullable=False),sa.Column("content_json",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False)); op.create_index("ix_cms_page_sections_page_id","cms_page_sections",["page_id"]); op.create_index("ix_cms_page_sections_section_key","cms_page_sections",["section_key"])
    op.create_table("cms_navigation_items",sa.Column("id",sa.String(36),primary_key=True),sa.Column("location",sa.String(32),nullable=False),sa.Column("label",sa.String(100),nullable=False),sa.Column("url",sa.String(300),nullable=False),sa.Column("position",sa.Integer(),nullable=False),sa.Column("is_visible",sa.Boolean(),nullable=False),sa.Column("open_new_tab",sa.Boolean(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False)); op.create_index("ix_cms_navigation_items_location","cms_navigation_items",["location"])
    op.create_table("cms_site_settings",sa.Column("key",sa.String(120),primary_key=True),sa.Column("value_json",sa.Text(),nullable=False),sa.Column("group_name",sa.String(60),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False)); op.create_index("ix_cms_site_settings_group_name","cms_site_settings",["group_name"])
    op.create_table("cms_content_revisions",sa.Column("id",sa.Integer(),primary_key=True,autoincrement=True),sa.Column("entity_type",sa.String(40),nullable=False),sa.Column("entity_id",sa.String(80),nullable=False),sa.Column("snapshot_json",sa.Text(),nullable=False),sa.Column("actor_user_id",sa.String(36),nullable=True),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_cms_content_revisions_entity_type","cms_content_revisions",["entity_type"]); op.create_index("ix_cms_content_revisions_entity_id","cms_content_revisions",["entity_id"]); op.create_index("ix_cms_content_revisions_created_at","cms_content_revisions",["created_at"])

def downgrade():
    for t in ["cms_content_revisions","cms_site_settings","cms_navigation_items","cms_page_sections","cms_pages"]: op.drop_table(t)
