"""align cms pages uniqueness
Revision ID: ce2ca901d043
Revises: 0005_seo_publishing
Create Date: 2026-09-30 02:39:27.263533
"""
from alembic import op
import sqlalchemy as sa

revision = 'ce2ca901d043'
down_revision = '0005_seo_publishing'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cms_pages_route_key'), 'cms_pages', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('cms_pages_route_key'), 'cms_pages', ['route'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
